spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/SpringReactTest
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver